services:
  proxy1:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy1
    networks:
      test-network:
        ipv4_address: 172.18.0.21 # Static IP for Proxy1
    expose:
      - "6000"
    ports:
      - "6001:6000" # Map port 6000 in the container to 6001 on the host for proxy1
    privileged: true
    command: /bin/sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && python proxy.py"

  proxy2:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy2
    networks:
      test-network:
        ipv4_address: 172.18.0.22 # Static IP for Proxy2
    expose:
      - "6000"
    ports:
      - "6002:6000" # Map port 6000 in the container to 6002 on the host for proxy2
    privileged: true
    command: /bin/sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && python proxy.py"

  proxy3:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy3
    networks:
      test-network:
        ipv4_address: 172.18.0.23 # Static IP for Proxy3
    expose:
      - "6000"
    ports:
      - "6003:6000" # Map port 6000 in the container to 6003 on the host for proxy3
    privileged: true
    command: /bin/sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && python proxy.py"

  master:
    build:
      context: ./master
      dockerfile: Dockerfile.master
    container_name: master
    networks:
      test-network:
        ipv4_address: 172.18.0.10 # Static IP for the Master
    stdin_open: true
    tty: true
    depends_on:
      - proxy1
      - proxy2
      - proxy3
    ports:
      - "8080:8080"

  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile.nest
    container_name: nest
    networks:
      test-network:
        ipv4_address: 172.18.0.30 # Static IP for the Nest
    expose:
      - "5000"
    ports:
      - "5002:5000"

  client_user:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: client_user
    networks:
      test-network:
        ipv4_address: 172.18.0.100 # Static IP for Client 1
    depends_on:
      - proxy1

#  client_attacker:
#    build:
#      context: ./client
#      dockerfile: Dockerfile.client
#    container_name: client_attacker
#    networks:
#      test-network:
#        ipv4_address: 172.18.0.110 # Static IP for Client 2
#    depends_on:
#      - proxy1
#    environment:
#      - SLEEP_INTERVAL=3

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
    external: true
