services:
  proxy1:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy1
    networks:
      test-network:
        ipv4_address: 172.18.0.21 # Static IP for Proxy1
    depends_on:
      - emqx-dashboard
    ports:
      - "6001:6000" # Map port 6000 in the container to 6001 on the host for proxy1
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && python proxy.py"

  proxy2:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy2
    networks:
      test-network:
        ipv4_address: 172.18.0.22 # Static IP for Proxy2
    depends_on:
      - emqx-dashboard
    ports:
      - "6002:6000" # Map port 6000 in the container to 6002 on the host for proxy2
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && python proxy.py"

  proxy3:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy3
    networks:
      test-network:
        ipv4_address: 172.18.0.23 # Static IP for Proxy3
    depends_on:
      - emqx-dashboard
    ports:
      - "6003:6000" # Map port 6000 in the container to 6003 on the host for proxy3
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && python proxy.py"

  master:
    build:
      context: ./master
      dockerfile: Dockerfile.master
    container_name: master
    networks:
      test-network:
        ipv4_address: 172.18.0.10 # Static IP for the Master
    stdin_open: true
    tty: true
    depends_on:
      - proxy1
      - proxy2
      - proxy3
      - emqx-dashboard
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1

  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile.nest
    container_name: nest
    networks:
      test-network:
        ipv4_address: 172.18.0.30 # Static IP for the Nest
    expose:
      - "5000"
    ports:
      - "5002:5000"
    environment:
      - PYTHONUNBUFFERED=1
    privileged: true  # Enable privileged mode for elevated permissions
    cap_add:
      - NET_ADMIN  # Allow the container to modify network configurations
      - SYS_ADMIN  # Allow sysctl changes
      
  client_user:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: client_user
    networks:
      test-network:
        ipv4_address: 172.18.0.100 # Static IP for Client 1
    depends_on:
      - proxy1
    environment:
      - PYTHONUNBUFFERED=1

  emqx-dashboard:
    image: emqx/emqx
    container_name: emqx-dashboard
    networks:
      test-network:
        ipv4_address: 172.18.0.60
    ports:
      - "8081:18083" # Web UI access
      - "1883:1883" # MQTT Protocol
      - "8084:8084" # WebSocket Protocol
    environment:
      EMQX_ALLOW_ANONYMOUS: "true" # Allow anonymous connections for testing

  client_attacker1:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker1
    networks:
      test-network:
        ipv4_address: 172.18.0.111
    depends_on:
      - proxy1

  client_attacker2:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker2
    networks:
      test-network:
        ipv4_address: 172.18.0.112
    depends_on:
      - proxy1

  client_attacker3:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker3
    networks:
      test-network:
        ipv4_address: 172.18.0.113
    depends_on:
      - proxy1

  client_attacker4:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker4
    networks:
      test-network:
        ipv4_address: 172.18.0.114
    depends_on:
      - proxy1

  client_attacker5:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker5
    networks:
      test-network:
        ipv4_address: 172.18.0.115
    depends_on:
      - proxy1

  client_attacker6:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker6
    networks:
      test-network:
        ipv4_address: 172.18.0.116
    depends_on:
      - proxy1

  client_attacker7:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker7
    networks:
      test-network:
        ipv4_address: 172.18.0.117
    depends_on:
      - proxy1

  client_attacker8:
    build:
      context: ./attacker
      dockerfile: Dockerfile.attacker
    container_name: client_attacker8
    networks:
      test-network:
        ipv4_address: 172.18.0.118
    depends_on:
      - proxy1

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
