version: '3'
services:
  proxy1:
    build:
      context: ./proxy
      dockerfile: Dockerfile.proxy
    container_name: proxy1
    networks:
      - test-network
    expose:
      - "5000"
    ports:
      - "5001:5000"
    privileged: true

  master:
    build:
      context: ./master
      dockerfile: Dockerfile.master
    container_name: master
    networks:
      - test-network
    stdin_open: true
    tty: true

  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile.nest
    container_name: nest
    networks:
      - test-network
    expose:
      - "5000"
    ports:
      - "5002:5000"

networks:
  test-network:
    driver: bridge
