# Dockerfile for Master
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Install curl and any necessary packages
RUN apt-get update && apt-get install -y \
    iputils-ping \
    traceroute \
    iproute2 \
    curl 

# Install DNS server
RUN pip install dnslib 

# Copy the master script to the container
COPY master.py /app/master.py

# Run the master app continuously for user input
CMD ["python", "-u", "master.py"]
