# Dockerfile for Master
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the master script to the container
COPY master.py /app/master.py

# Run the master app continuously for user input
CMD ["python", "-u", "master.py"]
