FROM python:3.9-slim

# Install nftables, iproute2, ping, and traceroute
RUN apt-get update && apt-get install -y \
    nftables \
    iproute2 \
    iputils-ping \
    traceroute \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the proxy script
COPY proxy.py /app/proxy.py

# Expose the TCP ports used for communication
EXPOSE 6000
EXPOSE 5000

# Run the proxy server
CMD ["python","-u", "proxy.py"]
